env:
  browser: true
  es6: true
extends: ["airbnb", "plugin:@typescript-eslint/recommended", "plugin:import/typescript"]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins: ["@typescript-eslint"]
rules: {
  react/jsx-one-expression-per-line: 'off',
  react/button-has-type: 'off',
  react/destructuring-assignment: [0],
  react/prop-types: 'off',
  jsx-a11y/no-noninteractive-tabindex: 'off',
  import/extensions: 'off',
  object-curly-newline: 'off',
  no-use-before-define: 'off',
  "@typescript-eslint/no-use-before-define": ["error"],
  react/jsx-filename-extension: [1, { "extensions": [".tsx", ".ts"] }],
  indent: "off",
  "@typescript-eslint/indent": ["error", 2],
  max-len: 'off',
}
